"""adiciona desconto ao atendimento

Revision ID: 97011b40df25
Revises: 84d824514852
Create Date: 2026-07-30 23:33:58.475989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97011b40df25'
down_revision = '84d824514852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desconto', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendimento', schema=None) as batch_op:
        batch_op.drop_column('desconto')

    # ### end Alembic commands ###
